#### Numpy
Numpy is a fundamental library for scientific compiting in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

In [1]:
import numpy as np

# Create array using numpy
# create a 1D array

arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [ ]:
# 1-D array
arr2 = np.array([1,2,3,4,5,6])
print(arr2.reshape(2,3)) # .reshape(row, column)
print(arr2.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [6]:
arr2 = np.array([[1,2,3,4,5,6]])
arr2.shape

(1, 6)

In [ ]:
# 2-D array
arr2 = np.array([[1,2,3,4,5,6], [3,4,5,6,7,8]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5 6]
 [3 4 5 6 7 8]]
(2, 6)


In [10]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((5, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape: ", arr.shape)
print("Number of dimensions: ", arr.ndim)
print("Size (number of elements): ", arr.size)
print("Data type: ", arr.dtype) # may vary based on platform
print("Item size (in bytes): ", arr.itemsize) # may vary based on platform

Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Data type:  int64
Item size (in bytes):  8


In [17]:
# Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element Wise addition
print("Addition: ", arr1 + arr2)

# Element Wise subtraction
print("Substraction: ",arr1 - arr2)

# Element Wise multiplication
print("Multiplication: ", arr1 * arr2)

# Element Wise division
print("Division: ", arr1 / arr2)

Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [18]:
# Universal Function
arr = np.array([2,3,4,5,6])

# Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural Log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [20]:
# array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr[0][0])

np.int64(1)

In [ ]:
arr[1:]